import requests
import pandas as pd
import time

# --- CONFIGURATION ---
API_KEY = "<use your API>"
COMPANY_LIST = [
    "Steinbeis- IFEM Augsburg Business School",
    "2G Energy AG",
    "3Degrees Group Inc.",
    "450connect GmbH",
    "50,2 Magazin - sig Media GmbH & Co. KG",
    "50Hertz Transmission GmbH",
    "@-yet GmbH",
    "A/V/E GmbH",
    "A4I Leipzig GmbH",
    "ABN AMRO Clearing Bank NV",
    "ACCESA IT SYSTEMS SRL",
    "ACT Group",
    "ADD GRUP",
    "ADEX Energy",
    "AFRY Management Consulting GmbH",
    "AFS Energy",
    "AGAT CO., LTD.",
    "AKTIF Technology GmbH",
    "ALTEN GmbH",
    "AMPLIFINO",
    "ANE Energy",
    "ANYbotics AG",
    "APROVIS Energy Systems GmbH",
    "ARGE DV e.V.",
    "ARGEnergie e.V.",
    "ARK Energy Consulting Limited",
    "ASP Metering GmbH",
    "ATEC GmbH & Co. KG",
    "AUCOTEC AG",
    "AVANTAG ENERGY S.à r.l.",
    "AVAT Automation GmbH",
    "AXP Consulting GmbH & Co. KG",
    "AXXCON GmbH & Co. KG",
    "Aareal Bank AG",
    "Abaxx Commodity Futures Exchange and Clearinghouse",
    "Acal BFi Germany GmbH",
    "Accenture",
    "Actility",
    "Adaptive Balancing Power GmbH",
    "Addsecure Digicomm GmbH",
    "Aeonic Data GmbH (BOOST-Community)",
    "Air Products GmbH",
    "Airpelago AB",
    "Alba Soluzioni S.r.l.",
    "Allianz Trade",
    "Alpha NT GmbH",
    "Alpha-Omega Technology GmbH & Co. KG",
    "Alpiq AG",
    "Amprion GmbH",
    "Anew Climate Europe GmbH",
    "Anfimau Industry Solutions GmbH",
    "Apator SA",
    "Apollo Green Solutions",
    "Arbeitsgemeinschaft für sparsame Energie- und Wasserverwendung (ASEW)",
    "ArcMind Technologies GmbH",
    "Argus Media Ltd.",
    "Arkion Solutions AB",
    "Artelys",
    "Arvato Systems",
    "Asseco BERIT GmbH",
    "Atmospheric G2",
    "Atos Information Technology GmbH",
    "Aurora Energy Research",
    "Aurora Systems",
    "Aurora by Sigholm",
    "Auxilius Services GmbH",
    "Avasition GmbH",
    "AvePoint Deutschland GmbH",
    "Axpo Group",
    "B&W Energy GmbH & Co. KG",
    "BAERIS Energie- & Messetechnik GmbH",
    "BAYOOTEC - Digitale Transformation in der Energiewirtschaft",
    "BBH AG Wirtschaftsprüfungsgesellschaft",
    "BBH Consulting AG",
    "BBH Engineering GmbH",
    "BBH Rechtsanwälte Steuerberater Unternehmensberater PartGmbB",
    "BBH Solutions AG",
    "BBL Company",
    "BCG Platinion",
    "BEMD",
    "BET Consulting GmbH",
    "BEZ TRANSFORMATORY, a.s.",
    "BFE Institut für Energie und Umwelt GmbH",
    "BKW",
    "BLICKER",
    "BNP Paribas",
    "BOM",
    "BOOST-Community",
    "BOTfriends GmbH",
    "BP Gas Marketing Ltd.",
    "BRYCK Startup Alliance GmbH",
    "BSI Software",
    "BTC Business Technology Consulting AG",
    "Bamboo Energy",
    "Bank of America / BofA Securities",
    "Baringa",
    "BayWa r.e. AG",
    "Bayern Innovativ GmbH",
    "Bayern International GmbH",
    "Beckhoff Automation GmbH & Co. KG",
    "Beijing HyperStrong Technology Co., Ltd.",
    "Berg GmbH",
    "Berlin Partner für Wirtschaft und Technologie GmbH",
    "Beschaffung aktuell - Konradin-Verlag Robert Kohlhammer GmbH",
    "Betterspace GmbH",
    "Billogram AB",
    "Bit2win Srl",
    "BitWatt Systems GmbH",
    "Blindleister",
    "Bloomberg L.P",
    "Brady Technologies",
    "Brahms Nebel & Kollegen",
    "Brainergy Park Energie GmbH",
    "Brandeis Digital GmbH",
    "Brandenburgische Technische Universität Cottbus-Senftenberg",
    "BritNed",
    "Brunel GmbH",
    "Bundesamt für Sicherheit in der Informationstechnik (BSI)",
    "CAIGOS GmbH",
    "CANCOM GmbH",
    "CEEGEX Ltd.",
    "CESS Clean Energy System Solutions GmbH",
    "CFP Energy",
    "CGI Deutschland B.V. & Co. KG",
    "CIC Japan Innovation Services G.K.",
    "CME Group",
    "COM plan + service Gesellschaft für Telekommunikation, Planung und Service mbH",
    "COMAN Software GmbH",
    "CONUTI GmbH",
    "CONVOTIS CS GmbH",
    "CST energy services GmbH",
    "CURSOR Software AG",
    "CWAN (Clearwater Analytics)",
    "Caely Renewables B.V.",
    "Caldera - Zero Carbon Industrial Heat",
    "Campus-EW GmbH",
    "Capalo AI",
    "CapeVision GmbH",
    "Capgemini Deutschland GmbH",
    "Cariqa",
    "Catalyst Commodities",
    "Caterpillar Energy Solutions GmbH",
    "Ceenergynews - White Paper Consulting Kft.",
    "Celsio GmbH",
    "Celsius Climate Solutions GmbH",
    "Central European Gas Hub AG",
    "Centrica Energy",
    "Certified Security Operations Center GmbH - CSOC",
    "Cintoo",
    "Citadel FlexPower GmbH",
    "Citigroup",
    "Clean Energy Valley - Kieler Wirtschaftsförderungs- und Strukturentwicklungs GmbH",
    "Cleanworld AS",
    "Commerzbank AG",
    "Companion.energy",
    "ConVista Consulting AG",
    "ConnectPoint GmbH",
    "Consolinno Energy GmbH",
    "Consurance GmbH",
    "CorreggioNET DMCC",
    "CreaTech Engineering GmbH",
    "Creatica GmbH",
    "Creomnia GmbH",
    "CubeLogic",
    "CyberGrid GmbH",
    "Cybersense GmbH",
    "Cyfidelity Security Services GmbH",
    "DARZ GmbH",
    "DB Energie GmbH",
    "DEHN SE",
    "DEIF A/S",
    "DEKRA",
    "DEKRA Robotized & Remote Inspection",
    "DEM GmbH",
    "DMS Gruppe GmbH",
    "DMT ENERGY ENGINEERS GmbH - HydroHub",
    "DMT Engineering Surveying GmbH & Co. KG",
    "DS Digital Service GmbH",
    "DSC Unternehmensberatung und Software GmbH",
    "DTN",
    "DVGW Berufliche Bildung",
    "DVGW e.V.",
    "DZG Metering GmbH",
    "Danske Commodities A/S",
    "Dataciders GmbH",
    "Decentlab GmbH",
    "Decision Trees GmbH",
    "Deepsearch GmbH",
    "Deloitte",
    "Deutsche Bank AG",
    "Deutsche Energie-Agentur GmbH (dena)",
    "Deutsche Energy Terminal GmbH (DET)",
    "Deutsche Kreditbank AG",
    "Deutsche Post Adress",
    "Deutsches Zentrum für Luft- und Raumfahrt e.V. (DLR)",
    "Dexter Energy Services",
    "Die Netzwerkpartner e.V.",
    "DieEnergiekoppler GmbH",
    "Diehl Metering GmbH",
    "Digimondo GmbH",
    "Dr. Herwig GmbH",
    "Drago G@dgets GmbH",
    "Duferco Energia S.p.A.",
    "E-Proof GmbH",
    "E-Star Trading GmbH",
    "E-world energy & water GmbH",
    "E.ON SE",
    "E3-Magazin – B4Bmedia.net AG",
    "EAAZE GmbH",
    "EAD-portal.de - Tropal Media GmbH",
    "EC POWER GmbH",
    "EDF Trading",
    "EDF power solutions Deutschland GmbH",
    "EDP",
    "EEB ENERKO GmbH",
    "EEG Energie- Einkaufs- und Service GmbH",
    "EEG Hellweg-Sauerland eG",
    "EEP | your independent shipping partner",
    "EEX Group / European Energy Exchange AG (EEX)",
    "EFR GmbH",
    "EGS (EMH Grid Solution) GMBH & Co. KG",
    "ELMI Power GmbH",
    "EMH Energie-Messtechnik GmbH",
    "EMH metering GmbH & Co. KG",
    "EMQ Technologies",
    "ENEIDA.IO",
    "ENEKA Energie & Karten",
    "ENEQUI AB",
    "ENERGIFY by CFT GmbH",
    "ENERGINET Systemansvar A/S",
    "ENERGY HUB Port of Wilhemshaven",
    "ENERGY4U GmbH",
    "ENERGYNEST",
    "ENERTRAG SE",
    "ENFOR A/S",
    "ENGIE Deutschland GmbH",
    "ENGIE Global Energy Management & Sales",
    "ENLITE Management & Engineering GmbH",
    "ENQT GmbH",
    "ENTEGA Plus GmbH",
    "EP Commodities",
    "EP Energie Deutschland GmbH",
    "EP NL BV",
    "EP Produzione",
    "EPEX SPOT SE",
    "EPH Group",
    "EPLAN GmbH & Co. KG",
    "ES EversheimStuible Rechtsanwaltsgesellschaft mbH",
    "ESFORIN SE",
    "ESMIG",
    "ESN EnergieSystemeNord GmbH",
    "ETD Transformatory",
    "EVERBRIDGE",
    "EWE AG",
    "EWG - Essener Wirtschaftsförderungsgesellschaft mbH",
    "EXAA Abwicklungsstelle für Energieprodukte AG",
    "EasyMeter GmbH",
    "Eco-Insights Oy",
    "EcoPlanet Green Operations GmbH",
    "EcoPort813 e.V.",
    "Edge Datenwirtschaft",
    "Ei Electronics KG",
    "Einklang",
    "Electricity Maps",
    "Electricity Transmission Networks of France (RTE FRANCE)",
    "Eleks Holding OU",
    "Eliq AB",
    "Elprom Heavy Industries",
    "Eltel Networks GmbH / U-SERV",
    "Elvaco GmbH",
    "Emission Partner GmbH & Co. KG",
    "Emulate Energy",
    "EnBW Energie Baden-Württemberg AG",
    "Encavis",
    "Eneco Energy Trade",
    "Enecon Consulting GmbH",
    "Enel SpA",
    "EnerChase GmbH & Co KG",
    "Energie Informationsdienst - DVV Media Group GmbH",
    "Energie Quader GmbH",
    "Energie Südbayern GmbH",
    "Energie.de - VDE Verlag GmbH",
    "EnergieDock GmbH",
    "Energieforen Leipzig GmbH",
    "Energierechtseck",
    "Energy - publish-industryVerlag GmbH",
    "Energy Aspects",
    "Energy Business Review",
    "Energy Exemplar",
    "Energy Intelligence Hub",
    "Energy Metering Germany GmbH",
    "Energy One",
    "Energy Opticon AB",
    "Energy Project Solutions GmbH",
    "Energy Risk",
    "Energy Weather",
    "Energy2market GmbH",
    "EnergyMarketPrice",
    "EnergyStock B.V.",
    "Enerjisa Commodities",
    "Enerlabs GmbH",
    "Enerpipe GmbH",
    "Eneve",
    "Engelhart CTP Renewables GmbH",
    "Eni Global Energy Markets SpA",
    "EnopAI GmbH & Co. KG",
    "Enovos Energie Deutschland GmbH",
    "Enpulse Ventures GmbH",
    "Entelios AG",
    "Entrix GmbH",
    "EnviTec Biogas AG",
    "Equias",
    "Equinor ASA",
    "Ergosign GmbH",
    "Erneuerbare Energien Hamburg Clusteragentur GmbH",
    "ErneuerbareEnergien - Gentner Energy Media GmbH",
    "Ernst Heitland GmbH & Co. KG",
    "Esri Deutschland GmbH",
    "Eurasia Group",
    "EversheimStuible Treuberater GmbH",
    "EvoNex Pro B.V.",
    "Exnaton AG",
    "Exolink GmbH",
    "Exxeta AG",
    "FACTUR Billing Solutions GmbH",
    "FERCHAU GmbH",
    "FGSZ Ltd",
    "FIS Systeme GmbH / FIS Global",
    "FIV.Energy GmbH",
    "FORRS GmbH",
    "FPT Deutschland GmbH",
    "Fachverband Biogas e.V.",
    "FairConsult 24|7",
    "FairDigital 24|7 GmbH",
    "FfE",
    "Fichtner GmbH & Co. KG",
    "Fichtner IT Consulting GmbH",
    "Fidectus AG",
    "FinanceConnect Advisory SF GmbH",
    "First Climate",
    "First Financial Software GmbH",
    "Fischer Energy Consulting GmbH",
    "FlexHome.Energy GmbH",
    "Flixcheck GmbH",
    "Fluence Energy GmbH",
    "Fluxys",
    "Fluxys TENP GmbH",
    "Fortum",
    "Forvis Mazars",
    "Fraunhofer Energy Alliance",
    "Fraunhofer IEE",
    "Fraunhofer IEG",
    "Fraunhofer IOSB-AST",
    "Fraunhofer ITWM",
    "Fraunhofer UMSICHT",
    "Fraunhofer-Institut SCAI",
    "Fraunhofer-Institut ISE",
    "Freqcon GmbH",
    "Frey Import Services ORA / WEY",
    "Fuji Graphite Works Co., Ltd.",
    "Fukushima Prefectural Government",
    "GAS CONNECT AUSTRIA GmbH",
    "GASCADE Gastransport GmbH",
    "GBS Europa GmbH",
    "GEOMAGIC GmbH",
    "GET AG",
    "GET Sol 1 GmbH / Preisvergleich.de",
    "GETEC Daten- und Abrechnungsmanagement GmbH",
    "GETEC ENERGIE GmbH",
    "GISA GmbH",
    "GITO mbH Verlag",
    "GLS Mobility GmbH",
    "GO2 Markets GmbH",
    "GP JOULE GmbH",
    "GWAdriga GmbH & Co. KG",
    "GWF MessSysteme AG",
    "Garderos GmbH",
    "Gas Management Services Ltd.",
    "Gas Storage Denmark A/S",
    "Gas- und Wärme-Institut Essen e.V. (GWI)",
    "Gasunie Deutschland Transport Services GmbH",
    "GazelEnergie",
    "Geologischer Dienst NRW",
    "Georg Hagelschuer GmbH & Co. KG",
    "Glint Solar AS",
    "Global Factor",
    "Global Green Group",
    "Go-e GmbH",
    "GoCardless",
    "Google Cloud",
    "Gorilla",
    "Gossen Metrawatt GmbH",
    "Gotion Germany Battery GmbH",
    "Green Navigation GmbH",
    "Green Steps GmbH",
    "GreenGate AG",
    "GreenPocket GmbH",
    "GreenTrax",
    "Greenflash GmbH",
    "Gridcog",
    "Gridfuse GmbH",
    "Gridsphere SA",
    "H.E.A.T. Energie-Software GmbH",
    "H2UB GmbH",
    "H2med",
    "HEUKING",
    "HEXUM Földgáz Zrt.",
    "HORIZONTE-Group AG",
    "HUAWEI Technologies Deutschland GmbH",
    "HUPX Ltd.",
    "Hahn Softwareentwicklung GmbH",
    "Hansen Technologies",
    "Hausheld AG",
    "Hays AG",
    "Heartbeat AI GmbH",
    "Heaten Germany GmbH",
    "Heinz Lackmann GmbH & Co. KG",
    "HeizungsJournal Verlags GmbH",
    "Helvetia",
    "Heringer Consulting GmbH",
    "Hermann Pipersberg jr. GmbH",
    "Hitachi Energy",
    "Hochschule Hamm-Lippstadt",
    "Holley Technology Ltd.",
    "Honeywell International",
    "Horizon Flevoland",
    "Hosenso Gmbh & Co. KG",
    "Huber SE",
    "Hungarian Gas Storage Ltd.",
    "Hy.Region.Rhein.Ruhr e.V.",
    "Hybrid Greentech Energy Trading ApS",
    "Hydri AB",
    "Hydrogen Metropole Ruhr",
    "Hydromea",
    "Hydronext Inc,",
    "IBERDROLA S.A.",
    "IBK Ingenieur- und Unternehmensberatung",
    "IBM Deutschland GmbH",
    "ICIS",
    "ICS Business GmbH",
    "IFS Deutschland GmbH",
    "IIP Neon GmbH (DAH Gruppe)",
    "INCEPT4 GmbH",
    "INFOMOTION - The Data Performance Company",
    "INFOPLAN Gesellschaft für Wirtschaftsberatung mbH",
    "INNIO Jenbacher",
    "INSYS icom",
    "INTENSE AG",
    "IO-Dynamics GmbH",
    "ION Commodities",
    "IOmeter GmbH",
    "ISONA GmbH",
    "ITC AG",
    "ITVT Group - Stadtwerk365",
    "IVU Informationssysteme GmbH",
    "IZ Immobilien Zeitung",
    "IfE - Ingenieurbüro für Energiewirtschaft GmbH",
    "Industrieanzeiger - Konradin-Verlag Robert Kohlhammer GmbH",
    "Inercomp GmbH",
    "Informatica GmbH",
    "IngenieurNetzwerk Energie eG",
    "Ingenieurbüro Böker GmbH",
    "Initiativ",
    "InnovationQuarter",
    "InvaCon Dialog GmbH",
    "Iqony GmbH",
    "Iskraemeco d.d.",
    "J. Schneider Elektrotechnik GmbH",
    "JSC Ukrtransgaz",
    "JUNO Solar GmbH & Co. KG",
    "Janitza electronics GmbH",
    "Johnson Controls",
    "Jua.ai AG",
    "Jungle AI",
    "KA Korrespondenz Abwasser",
    "KALORIMETA GmbH (KALO)",
    "KB.energy GmbH",
    "KD Kommunal Direkt",
    "KEBA Energy Automation GmbH",
    "KELER CCP Ltd.",
    "KI-P GmbH",
    "KISTERS AG",
    "KMH GmbH",
    "KUGU Home GmbH",
    "KVK Kompetenzzentrum Verteilnetze und Konzessionen GmbH",
    "KWA Analytics",
    "KYOS Energy Analytics",
    "Kangoolutions GmbH",
    "Kelvin Green GmbH",
    "Kemna Druck Kamen GmbH",
    "Kempower",
    "Kerlink",
    "Kiona GmbH",
    "Kiwigrid GmbH",
    "Klafka & Hinz Energie-Informations-Systeme GmbH",
    "KlimaInvest Green Concepts GmbH",
    "Kompetenznetzwerk Umweltwirtschaft.NRW",
    "Konica Minolta Business Solutions Deutschland GmbH",
    "Kontron AIS GmbH",
    "Koyne-System-Elektronik",
    "Kpler Germany GmbH",
    "Kraftwerk Software",
    "Kraken",
    "Kremsmüller Anlagenbau GmbH",
    "Kuhse Power Solutions GmbH",
    "Kumandra Energy GmbH & Co. KG",
    "Kyoto Group",
    "LBA Luftbildauswertung GmbH",
    "LCP Delta",
    "LEAD Consult",
    "LEAG",
    "LEM-Software GmbH",
    "LMS Services GmbH & Co.KG",
    "LSEG",
    "Lacima Group",
    "Landesamt für Natur, Umwelt und Klima NRW",
    "Landeskoordinierungsstelle Elektromobilität SH",
    "Landesverband Erneuerbare Energie e.V. (LEE)",
    "Landis+Gyr GmbH",
    "Langmatz GmbH",
    "Lansen Systems AB",
    "Lantronix Inc.",
    "Layer Four GmbH & Co. KG",
    "Lemonbeat GmbH",
    "LevelTen Energy",
    "LiBrick ESS GmbH",
    "Liberaware Co., LTD.",
    "Lime Technologies Germany GmbH",
    "Little Oak Energy",
    "LivEye GmbH",
    "Lobaro GmbH",
    "Logarex Smart Metering, s.r.o.",
    "Lovion GmbH",
    "Lubit",
    "Lumenaza GmbH",
    "Lumera Energy GmbH",
    "MAX STRAUBE - Industrie - Anlagenbau",
    "MB Energy Holding GmbH & Co. KG",
    "MBS AG",
    "MC Technologies GmbH",
    "MClimate AD",
    "MET Group",
    "METAMO Energy",
    "MEVA ENERGY AB",
    "MITNETZ STROM",
    "MIVO Technology AB",
    "MRK Media AG",
    "MSA Safety",
    "MVM ONEnergy Zrt.",
    "MVV Energie AG",
    "Macquarie Bank Limited",
    "Magaldi Green Energy",
    "Magnus Energy",
    "Mako Software GmbH",
    "Mammut Energy AB",
    "Marex",
    "Mark-E Aktiengesellschaft",
    "Maschinenfabrik Reinhausen GmbH",
    "Materna Information & Communications SE",
    "Mechanocross Co., Ltd.",
    "Mersen Deutschland Eggolsheim GmbH",
    "Message Mobile GmbH",
    "MetCom Solutions GmbH",
    "MetDesk Limited",
    "Metacon AB",
    "Meteomatics AG",
    "Mettenmeier GmbH",
    "Midas Energy A/S",
    "MWIKE NRW",
    "Miromico AG",
    "Mitel (Unify)",
    "Mitsubishi Motors Deutschland",
    "Mitsui Bussan Commodities",
    "Molecule",
    "Montel",
    "Munich Re",
    "Murex",
    "Möhring Energie Holding GmbH",
    "N-ERGIE Aktiengesellschaft",
    "N.V. NOM",
    "N.V. Nederlandse Gasunie",
    "NAFTA a.s.",
    "NEW Niederrhein Energie und Wasser GmbH",
    "NGEN Germany GmbH",
    "NORTH-TEC Maschinenbau GmbH",
    "NRW.BANK",
    "NRW.Energy4Climate GmbH",
    "NTT DATA",
    "NUS Consulting Group",
    "NZR Nordwestdeutsche Zählerrevision GmbH",
    "NaTran (GRTgaz)",
    "NaTran Deutschland GmbH",
    "Nadara Energy Trading S.r.l.",
    "Nagarro ES GmbH",
    "Natixis Corporate & Investment Banking",
    "Natuvion GmbH",
    "Navitasoft Zrt.",
    "Netcom Connected Services GmbH",
    "Netherlands Pavillion",
    "Netze BW GmbH",
    "Netzkontor GmbH",
    "Netzwerkagentur Erneuerbare Energien SH",
    "NeuConnect Britain Ltd",
    "Nexiga GmbH",
    "Next Kraftwerke GmbH",
    "Nexus Nova GmbH",
    "NiCE Cognigy",
    "Ningbo Deye ESS Technology Co., Ltd.",
    "Nord Pool",
    "Nordeway Energy AB",
    "Norlys Energy Trading A/S",
    "Novalnet",
    "Novocarbo GmbH",
    "Novotrend GmbH",
    "Nowega GmbH",
    "Nvalue AG",
    "OGE (Open Grid Europe GmbH)",
    "OMV Gas Marketing & Trading GmbH",
    "ONERI",
    "ONTRAS Gastransport GmbH",
    "OPTIMAL SYSTEMS",
    "OPTIMIZE ENERGY",
    "ORBIS Energy & Utilities",
    "ORCHESTRADE",
    "ORCHIS Umweltplanung GmbH",
    "ORLEN",
    "ORLEN ENERGY TRADING GmbH",
    "OTT HydroMet GmbH",
    "Octopus Energy Germany GmbH",
    "Ogre AI",
    "Omexom Deutschland",
    "Oost NL",
    "Open Climate Fix",
    "OpenWeather",
    "Oracle",
    "Ore Energy B.V.",
    "Otark GmbH",
    "Otter Energy Trading GmbH",
    "OverIT",
    "P3 Group GmbH",
    "PEC project engineers & consultants GmbH",
    "PFALZWERKE AKTIENGESELLSCHAFT",
    "PHYSEC GmbH",
    "PONTON GmbH",
    "POWER SPRINTER GmbH",
    "PQ Plus GmbH",
    "PRISMA European Capacity Platform GmbH",
    "PRO ENERGY CONSULT GmbH",
    "PROLOGA GmbH",
    "PSI Software SE",
    "PUC antennas & equipment GmbH",
    "PagerDuty",
    "Paperfly",
    "Paragon Germany GmbH",
    "Paratus & Partners",
    "PensExpert GmbH",
    "Pepperl+Fuchs Vertrieb Deutschland GmbH",
    "Pexapark",
    "PicoCELA, Inc.",
    "Pionierkraft GmbH",
    "Pixii Germany GmbH",
    "Planys BV",
    "Planys Technologies",
    "Plexigrid",
    "Podero GmbH",
    "PortfolioEnergy",
    "PortfolioWerkStadt GmbH",
    "Power Plus Communications AG",
    "Power Reply GmbH",
    "PowerHive",
    "Powernaut",
    "Preisenergie GmbH",
    "Previse Systems AG",
    "PricewaterhouseCoopers GmbH WPG",
    "Projektron GmbH",
    "Prolan AG",
    "Prototype Club GmbH",
    "Protovation GmbH",
    "Puls GmbH",
    "Pythonian",
    "QUADRA Energy GmbH",
    "QUNDIS GmbH",
    "Quadient CXM Germany GmbH",
    "Quartierkraft GmbH",
    "Qurrent AB",
    "R Schmitt Enertec",
    "RAVENWITS",
    "RELAY GmbH",
    "REint",
    "RIVACON GmbH",
    "RIZM",
    "RJC Group",
    "ROM Utrecht Region",
    "ROOF+ GmbH",
    "RUHR PM GmbH",
    "RWE",
    "RWE Gas Storage West GmbH",
    "Raiffeisenbank a.s.",
    "Re-Twin Energy GmbH",
    "Reasonance GmbH",
    "Rechtsanwälte Achterwinter",
    "Renewcast Srl",
    "Reonic GmbH",
    "Repower AG",
    "Return",
    "Reverion GmbH",
    "Rhein Ruhr Power e.V.",
    "Rittal GmbH & Co. KG",
    "Robotron Datenbank-Software GmbH",
    "Rolls-Royce Power Systems",
    "S&P Global Global Energy",
    "SAMAWATT AG",
    "SAP Deutschland SE & Co. KG",
    "SCB Environmental Markets SA",
    "SCHUFA HOLDING AG",
    "SCHWARM Technologies Germany GmbH",
    "SE Scherbeck Energy GmbH",
    "SEEBURGER Deutschland GmbH & Co. KG",
    "SEFE",
    "SFC Energy AG",
    "SIV Utility Services GmbH",
    "SIV.AG",
    "SK Verbundenergie AG",
    "SME Management GmbH",
    "SMIGHT GmbH",
    "SMILICS TECHNOLOGIES SL",
    "SOKRATHERM GmbH",
    "SONNENENERGIE (DGS)",
    "SOPTIM AG",
    "SPRINT Robotics",
    "SPiNE",
    "STACKIT",
    "STORENGY",
    "STX Commodities B.V.",
    "SThree GmbH",
    "SUNCATCHER Engineering GmbH",
    "SV SparkassenVersicherung",
    "Sagemcom Dr. Neuhaus GmbH",
    "Sagemcom Fröschl GmbH",
    "SalesTown",
    "Salesfive",
    "Samp",
    "Scalefocus",
    "Schleupen SE",
    "Schneider Electric GmbH",
    "Schoenergie GmbH",
    "Second Foundation Germany GmbH",
    "Secure",
    "Securiton GmbH",
    "Sensaru GmbH",
    "SensorX Solutions AG",
    "Sentinum GmbH",
    "ServiceNow GmbH",
    "ServiceOcean SalesDE GmbH",
    "Shell Energy",
    "Shenzhen CLOUElectronics Co., Ltd.",
    "Sicherheits-Berater",
    "Siekerkotte GmbH & Co.KG",
    "Siqens GmbH",
    "Sirocco Energy SL",
    "Smart City Solutions GmbH",
    "SmartestEnergy Limited",
    "Snam S.p.A.",
    "Snowflake Computing GmbH",
    "Socomec GmbH",
    "SoftProject GmbH",
    "SolaX Power Europe GmbH",
    "Solandeo GmbH",
    "Solar Manager GmbH",
    "Solarize Energy Solutions GmbH",
    "Soluvia Energy Services GmbH",
    "Somentec Software GmbH",
    "Sontex Deutschland GmbH",
    "Sopra Steria SE",
    "SoutH2 Corridor",
    "South Pole",
    "Spacergy AB",
    "Spire Global",
    "Springer Fachmedien Wiesbaden GmbH",
    "Sprungwerk GmbH",
    "EFET",
    "Stadt Bottrop",
    "Stadt der Zukunft",
    "Stadt.Energie.Speicher GmbH",
    "Stadtwerke Duisburg Metering GmbH",
    "Stadtwerke Essen AG",
    "Stadtwerke Schwäbisch Hall GmbH",
    "Standard Chartered Bank AG",
    "Staqx B.V.",
    "Statkraft",
    "Stem GmbH",
    "StoneX",
    "Storengy Deutschland GmbH",
    "StormGeo Energy Analytics",
    "Stucke Elektronik GmbH",
    "Summit Energy Europe",
    "Sunnic Lighthouse GmbH",
    "Supercharge",
    "Swedish Energy Pavilion",
    "Swiss-SDI GmbH",
    "Swistec GmbH",
    "Switzerland Global Enterprise",
    "Synergi",
    "System Brain Corporation",
    "T-Systems International GmbH",
    "TAG GmbH",
    "TAP Steuerungsgesellschaft mbH & Co. KG",
    "TAQA Energy B.V.",
    "TESVOLT AG",
    "THEMA Consulting Deutschland GmbH",
    "TOCOM (JPX Group)",
    "TOP-Energy",
    "TRICERA energy GmbH",
    "TSUZUKI Co., Ltd",
    "Tagueri AG",
    "Taktsoft GmbH",
    "Tauber Energy GmbH",
    "Tauber Solar Holding GmbH",
    "Team EDDA",
    "Teamwire",
    "TechniSat Digital GmbH",
    "Gateway49",
    "TelePower GmbH & Co. KG",
    "Telefónica Germany GmbH & Co. OHG",
    "Teos Energy GmbH",
    "Teréga",
    "The MathWorks GmbH",
    "The Mobility House Energy GmbH",
    "TheStorage / Buffer Solutions Oy",
    "Theben Smart Energy GmbH",
    "Themen Magazin",
    "Thoughtworks",
    "Thyssengas GmbH",
    "Thüga Erneuerbare Energien GmbH & Co. KG",
    "Tilt Energy",
    "Time2Market ApS",
    "TokWise Ltd.",
    "Tokyo Metropolitan Government",
    "Topaz Technology",
    "Topcom Kommunikationssysteme GmbH",
    "TotalEnergies",
    "Trading Hub Europe GmbH",
    "Trading Technologies International, Inc.",
    "Transfer-Hub Klimaneutrales Wirtschaften SH",
    "Trassify GmbH",
    "Trayport Limited",
    "Trend Micro",
    "Trianel GmbH",
    "Tridens",
    "Trinitatum",
    "Trio",
    "Truxel AB",
    "Tyczka Hydrogen GmbH",
    "TÜV Informationstechnik GmbH",
    "TÜV NORD CERT",
    "TÜV NORD EnSys GmbH & Co. KG",
    "TÜV Süd Industrie Service GmbH",
    "TÜV TRUST IT GmbH",
    "UID GmbH",
    "UNITRONIC GmbH",
    "UTILIGENCE GmbH",
    "UTILITY PARTNERS GmbH",
    "Umweltbundesamt",
    "UniCredit",
    "Unigy GmbH",
    "Uniper SE",
    "Univers",
    "Urban Solar AG",
    "Urbio",
    "UseTree GmbH",
    "VDE DKE",
    "VDE Prüf- und Zertifizierungsinstitut GmbH",
    "VEA e.V.",
    "VEGA Grieshaber KG",
    "VERBUND AG",
    "VIDEC Data Engineering GmbH",
    "VIK e.V.",
    "VIVAVIS AG",
    "VK Energie GmbH",
    "VNG Gasspeicher GmbH",
    "VNG Handel & Vertrieb GmbH",
    "VOLUE AS",
    "VT Electron",
    "VTC Teknoloji Enerji Limited Sirketi",
    "VU-ARGE",
    "Vaisala Xweather",
    "Value Creed LLC",
    "Vattenfall Energy Trading GmbH",
    "VdW Rheinland Westfalen e.V.",
    "Vega Insight AS",
    "Venios GmbH",
    "Ventriks",
    "VKU",
    "Verbio SE",
    "Versorger-Allianz 450",
    "VertiGIS",
    "Vertis Environmental Finance",
    "Viessmann Deutschland GmbH",
    "Vireo Ventures",
    "Virtimo AG",
    "Virtual Global Trading AG",
    "Vodafone IoT GmbH",
    "Volatile GmbH",
    "Voltfang GmbH",
    "Voltwise DE GmbH",
    "WAGO GmbH & Co. KG",
    "WATTICAL Energon Tech GmbH",
    "WCG Wärme Contracting",
    "WEPTECH elektronik GmbH",
    "WIKA Alexander Wiegand SE & Co. KG",
    "WTSH GmbH",
    "Weidmüller Interface GmbH & Co. KG",
    "Wertefest GmbH & requisimus AG",
    "Westenergie AG",
    "Whiffle B.V.",
    "WiN Emscher-Lippe",
    "WiR Solutions GmbH",
    "Wilken Software Group",
    "Wireless Logic mdex GmbH",
    "Wirepas",
    "Wirtschaftsförderung Bochum WiFö GmbH",
    "Wisdom Bridge AI GmbH",
    "Wiseglow Deutschland",
    "Withthegrid",
    "Wood Mackenzie",
    "World Climate Service",
    "Worldgrid",
    "XPhone Connect",
    "Xtra-energy",
    "X‑impuls AG",
    "Yes Energy",
    "Yokogawa Deutschland GmbH",
    "Yuon Control AG",
    "ZE Energy Inc.",
    "ZENNER International GmbH & Co.",
    "ZFK",
    "Zaphiro Technologies SA",
    "Zema",
    "Zema Global",
    "Zentrum für Digitale Entwicklung GmbH",
    "Zerofy",
    "Zscaler Germany GmbH",
    "Zukunftsagentur Rheinisches Revier GmbH",
    "Zukunftscluster ETOS",
    "Zympler",
    "Zählerfreunde GmbH",
    "adesso SE",
    "admi Kommunal GmbH",
    "advalju GmbH & Co. KG",
    "advizeo by Hager",
    "agriportance GmbH",
    "aiESG, Inc.",
    "aimpera GmbH",
    "alitiq GmbH",
    "aov IT.Services GmbH",
    "autarc GmbH",
    "avoltra GmbH",
    "batch2 engineering GmbH",
    "bayernets GmbH",
    "be.storaged GmbH",
    "berta & rudi",
    "bikosigma GmbH",
    "bmp greengas GmbH",
    "bpc AG",
    "brand eins",
    "brandseven GmbH",
    "busitec GmbH",
    "capSpire",
    "caplog-x GmbH",
    "carbonify GmbH",
    "cerebricks GmbH",
    "chargecloud GmbH",
    "citiworks AG",
    "clarifydata GmbH",
    "clever-PV GmbH",
    "co.met GmbH",
    "collect Artificial Intelligence GmbH",
    "comtac AG",
    "comtime GmbH",
    "con terra GmbH",
    "conenergy ag",
    "conenergy agentur gmbh",
    "conenergy akademie",
    "conenergy consult gmbh",
    "conet Holding GmbH",
    "conscoo GmbH",
    "cortility gmbh",
    "cronos Unternehmensberatung GmbH",
    "d-fine GmbH",
    "dLaboratory Sweden AB",
    "deeeper.technology GmbH",
    "dezera GmbH",
    "dimater GmbH",
    "dispoEnergy",
    "dvlp.energy GmbH",
    "eBZ GmbH",
    "eClou GmbH",
    "eRound",
    "econ solutions GmbH",
    "ecorize",
    "elektroautomobil",
    "elementa GmbH & Co. KG",
    "elevait GmbH & Co. KG",
    "emsys VPP GmbH",
    "emsys grid services GmbH",
    "emw - energate GmbH",
    "encentive GmbH",
    "encoord GmbH",
    "endanet GmbH",
    "endios GmbH",
    "ene't GmbH",
    "enercast GmbH",
    "energate gmbh",
    "energethik ingenieurgesellschaft",
    "energie.blog",
    "energielenker solutions GmbH",
    "energy & meteo systems GmbH",
    "energynet.de",
    "enermore GmbH",
    "enersis suisse AG",
    "enervis energy advisors GmbH",
    "enmacc GmbH",
    "enmore consulting ag",
    "enneo GmbH",
    "enprout gmbh",
    "ensight",
    "ensight PartG mbH",
    "enspired",
    "envelio GmbH",
    "enwarp gmbh",
    "epilot",
    "essociation",
    "esterion GmbH",
    "estoma Co.,Ltd",
    "ev-pay GmbH",
    "evu zählwerk",
    "eweco GmbH",
    "exceeding solutions GmbH",
    "eyerod",
    "fination services GmbH",
    "genua GmbH",
    "getdigital solutions GmbH",
    "greenventory GmbH",
    "gwf Gas+Energie",
    "h2-netzwerk-ruhr e.V.",
    "hibot Corporation",
    "hsag Heidelberger Services AG",
    "iNeG",
    "imovis GmbH",
    "in.power Services GmbH",
    "inexogy smart metering GmbH & Co. KG",
    "inno2grid GmbH",
    "innogy Ceska republika a.s.",
    "PROvendis GmbH",
    "inovoo GmbH",
    "ipushpull",
    "ista SE",
    "it-novum GmbH",
    "items GmbH",
    "iteratec GmbH",
    "k3i GmbH",
    "koenig.solutions GmbH",
    "korero GmbH",
    "krumedia GmbH",
    "kuafu AG",
    "ladenetz.de",
    "levitate aerospace gmbh",
    "m2g-Consult GmbH",
    "m2m Germany",
    "m3 management consulting GmbH",
    "me energy Technologies GmbH",
    "meonet GmbH",
    "metiundo GmbH",
    "metrify smart metering GmbH",
    "mgm consulting partners",
    "minimum energy GmbH",
    "neugemacht GmbH",
    "nextract energy",
    "nobile",
    "node.energy GmbH",
    "noventic GmbH",
    "novomind AG",
    "onu.energy GmbH",
    "openKONSEQUENZ eG",
    "osapiens Holding GmbH",
    "othermo GmbH",
    "pattr GmbH",
    "phi-Consulting GmbH",
    "phi-Service GmbH",
    "pironex technology GmbH",
    "pixolus GmbH",
    "plenum AG Management Consulting",
    "prego services GmbH",
    "providata GmbH",
    "pure.energy GmbH",
    "pv magazine",
    "q-bility GmbH",
    "r2b energy consulting GmbH",
    "re-sult AG",
    "rebase.energy",
    "regiocom SE",
    "requisimus",
    "retoflow GmbH",
    "rheNEO GmbH",
    "rhenag Rheinische Energie AG",
    "rhenag legal Rechtsanwalt GmbH",
    "rku.it GmbH",
    "salesforce.com Germany GmbH",
    "sbc soptim business consult GmbH",
    "smartmove@energie GmbH",
    "solvimus GmbH",
    "stadt+werk",
    "stp.one",
    "succedo Unternehmensberatung GmbH",
    "suena GmbH",
    "suportica GmbH",
    "taod Consulting GmbH",
    "telent GmbH",
    "terralayr Germany GmbH & Co. KG",
    "terranets bw GmbH",
    "thüga solutions GbR",
    "timpetools GbR",
    "touchwert",
    "trawa",
    "trend:research GmbH",
    "triPica",
    "trurnit GmbH",
    "uberall",
    "valantic GmbH",
    "vaylens GmbH",
    "vgbe energy Service e.V.",
    "wattline GmbH",
    "work digital GmbH",
    "worldiety GmbH",
    "wpd GmbH",
    "xpertnova GmbH",
    "Å Energi AS",
    "ÖKOTEC Energiemanagement GmbH",
    "Ørsted"
]

def search_company_info(company_name):
    url = "https://google.serper.dev/search"
    # We ask Google for the website and main socials in one go
    query = f"{company_name} official website linkedin facebook twitter"
    
    payload = {"q": query, "num": 10}
    headers = {'X-API-KEY': API_KEY, 'Content-Type': 'application/json'}
    
    try:
        response = requests.post(url, headers=headers, json=payload)
        results = response.json().get('organic', [])
        
        data = {
            "Company": company_name,
            "Website": "",
            "LinkedIn": "",
            "Facebook": "",
            "X_Twitter": ""
        }

        for res in results:
            link = res.get('link', '').lower()
            # Basic logic to categorize links
            if "linkedin.com/company" in link and not data["LinkedIn"]:
                data["LinkedIn"] = res.get('link')
            elif "facebook.com" in link and not data["Facebook"]:
                data["Facebook"] = res.get('link')
            elif ("twitter.com" in link or "x.com" in link) and not data["X_Twitter"]:
                data["X_Twitter"] = res.get('link')
            elif not data["Website"] and not any(x in link for x in ["linkedin", "facebook", "twitter", "x.com", "instagram", "youtube"]):
                data["Website"] = res.get('link')
        
        return data
    except Exception as e:
        print(f"Error searching for {company_name}: {e}")
        return None

# --- EXECUTION ---
final_data = []
for name in COMPANY_LIST:
    print(f"Searching for: {name}...")
    info = search_company_info(name)
    if info:
        final_data.append(info)
    time.sleep(0.1)  # Slight delay to avoid rate limits

# Save to Excel/CSV
df = pd.DataFrame(final_data)
df.to_csv("company_research.csv", index=False)
print("Done! Check company_research.csv")